#include <ios>
using std::ios;
#include <sstream>
#include <iomanip>
using std::stringstream;
using std::istringstream;
using std::ostringstream;
using std::hex;
using std::setfill;
using std::setw;
using std::fixed;
using std::setprecision;
